services:
  app:
    container_name: wallet
    build:
      context: ./
    environment:
      - SERVER_ADDRESS
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DATABASE
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - wallet-network

  postgres:
    image: "postgres:15-alpine"
    ports:
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DATABASE
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - wallet-network

volumes:
  db_data:
    driver: local

networks:
  wallet-network: